/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OriginsRouteImport } from './routes/origins'
import { Route as HomecomingRouteImport } from './routes/homecoming'
import { Route as EmergingRouteImport } from './routes/emerging'
import { Route as CrossroadsRouteImport } from './routes/crossroads'
import { Route as BecomingRouteImport } from './routes/becoming'
import { Route as IndexRouteImport } from './routes/index'

const OriginsRoute = OriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => rootRouteImport,
} as any)
const HomecomingRoute = HomecomingRouteImport.update({
  id: '/homecoming',
  path: '/homecoming',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergingRoute = EmergingRouteImport.update({
  id: '/emerging',
  path: '/emerging',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossroadsRoute = CrossroadsRouteImport.update({
  id: '/crossroads',
  path: '/crossroads',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomingRoute = BecomingRouteImport.update({
  id: '/becoming',
  path: '/becoming',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/crossroads': typeof CrossroadsRoute
  '/emerging': typeof EmergingRoute
  '/homecoming': typeof HomecomingRoute
  '/origins': typeof OriginsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/crossroads': typeof CrossroadsRoute
  '/emerging': typeof EmergingRoute
  '/homecoming': typeof HomecomingRoute
  '/origins': typeof OriginsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/crossroads': typeof CrossroadsRoute
  '/emerging': typeof EmergingRoute
  '/homecoming': typeof HomecomingRoute
  '/origins': typeof OriginsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/becoming'
    | '/crossroads'
    | '/emerging'
    | '/homecoming'
    | '/origins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/becoming'
    | '/crossroads'
    | '/emerging'
    | '/homecoming'
    | '/origins'
  id:
    | '__root__'
    | '/'
    | '/becoming'
    | '/crossroads'
    | '/emerging'
    | '/homecoming'
    | '/origins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomingRoute: typeof BecomingRoute
  CrossroadsRoute: typeof CrossroadsRoute
  EmergingRoute: typeof EmergingRoute
  HomecomingRoute: typeof HomecomingRoute
  OriginsRoute: typeof OriginsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/origins': {
      id: '/origins'
      path: '/origins'
      fullPath: '/origins'
      preLoaderRoute: typeof OriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homecoming': {
      id: '/homecoming'
      path: '/homecoming'
      fullPath: '/homecoming'
      preLoaderRoute: typeof HomecomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emerging': {
      id: '/emerging'
      path: '/emerging'
      fullPath: '/emerging'
      preLoaderRoute: typeof EmergingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossroads': {
      id: '/crossroads'
      path: '/crossroads'
      fullPath: '/crossroads'
      preLoaderRoute: typeof CrossroadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/becoming': {
      id: '/becoming'
      path: '/becoming'
      fullPath: '/becoming'
      preLoaderRoute: typeof BecomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomingRoute: BecomingRoute,
  CrossroadsRoute: CrossroadsRoute,
  EmergingRoute: EmergingRoute,
  HomecomingRoute: HomecomingRoute,
  OriginsRoute: OriginsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
